using System.Globalization;
using System.IO;
using System.Security.Cryptography;
using System.Text.Json;
using System.Text.RegularExpressions;
using AwesomeAssertions;
using AdTrim.Encoders;
using AdTrim.Models;
using AdTrim.Services;
using Xunit;

namespace AdTrim.Tests;

/// <summary>
/// End-to-end integration tests for ExportService against the 30-second
/// Rookie fixture (see fixtures/PROBE_REFERENCE.md "File 4"). Generated by
/// tools\make-test-fixture.cmd from the user's full Rookie recording.
///
/// Fixture discovery: ADTRIM_ROOKIE_30S_FIXTURE env var if set,
/// otherwise auto-discovered by walking up from the test bin dir looking
/// for fixtures/rookie-30s.mp4. Tests skip cleanly when the fixture is
/// absent so CI / a fresh clone won't fail.
///
/// What this covers that the per-segment encoder test in
/// FixtureIntegrationTests does NOT:
///   - The full RunExportAsync pipeline (multi-segment encode → concat
///     demuxer → chapter mux), not just BuildSegmentArgs.
///   - bin_data exclusion at the integration level (source has a
///     bin_data stream from the MP4 muxer; output must have at most one
///     - the muxer-injected chapter representation, never the source's).
///   - Picture-quality regression net via SSIM against the source.
///   - Output-path quoting on Windows paths with spaces + apostrophes.
/// </summary>
public class ExportIntegrationTests
{
    private static string? FindFixture()
    {
        var env = Environment.GetEnvironmentVariable("ADTRIM_ROOKIE_30S_FIXTURE");
        if (!string.IsNullOrEmpty(env) && File.Exists(env)) return env;

        // Walk upward from the test bin dir to find <repo>/fixtures/rookie-30s.mp4.
        var dir = AppContext.BaseDirectory;
        for (int i = 0; i < 8 && !string.IsNullOrEmpty(dir); i++)
        {
            var candidate = Path.Combine(dir, "fixtures", "rookie-30s.mp4");
            if (File.Exists(candidate)) return candidate;
            dir = Path.GetDirectoryName(dir);
        }
        return null;
    }

    private const string SkipReason =
        "30s Rookie fixture not found. Run tools\\make-test-fixture.cmd to generate it, " +
        "or set ADTRIM_ROOKIE_30S_FIXTURE to an explicit path.";

    private static string Sha256(string path)
    {
        using var fs = File.OpenRead(path);
        using var sha = SHA256.Create();
        return Convert.ToHexString(sha.ComputeHash(fs));
    }

    [SkippableFact]
    public async Task Export_MultiSegment_ProducesValidConcatenatedOutput()
    {
        var fixture = FindFixture();
        Skip.If(fixture is null, SkipReason);

        var hashBefore = Sha256(fixture!);
        var runner = new FfmpegRunner();
        var probe = new MediaProbeService(runner);
        var encoder = new LibX264EncoderStrategy();
        var export = new ExportService(runner, encoder);

        var media = await probe.ProbeAsync(fixture!);
        media.PrimaryAudio.Should().NotBeNull();

        // Three kept segments at [0-3, 7-13, 23-30] inside the 30s fixture.
        // Exercises: multi-segment encode, concat across boundaries, multi-
        // chapter mux, and the source-time → output-time offset accumulation
        // that the chapter metadata builder has to get right.
        var segments = new[]
        {
            new ExportSegment(0,          0,  3_000_000, "Part 1"),
            new ExportSegment(1,  7_000_000, 13_000_000, "Part 2"),
            new ExportSegment(2, 23_000_000, 30_000_000, "Part 3"),
        };
        long expectedDurMs = segments.Sum(s => s.DurationUs) / 1_000;  // 16_000

        var outDir = Path.Combine(Path.GetTempPath(), "AdTrim",
            "exp-test-" + Guid.NewGuid().ToString("n").Substring(0, 8));
        Directory.CreateDirectory(outDir);
        var outPath = Path.Combine(outDir, "export.mp4");

        try
        {
            var plan = new ExportPlan(
                SourcePath: fixture!,
                OutputPath: outPath,
                SourceDurationUs: media.DurationUs,
                PrimaryAudioStreamIndex: media.PrimaryAudio!.Index,
                KeptSegments: segments,
                FrameRate: media.FrameRate,
                PrimaryAudioCodec: media.PrimaryAudio.Codec);

            await export.RunExportAsync(plan);

            File.Exists(outPath).Should().BeTrue();
            new FileInfo(outPath).Length.Should().BeGreaterThan(500_000,
                because: "16s of 1080p h264 at CRF 20 should be well above 500KB");

            var probeR = await runner.RunFfprobeAsync(new[]
            {
                "-v", "error",
                "-print_format", "json",
                "-show_streams", "-show_format", "-show_chapters",
                outPath,
            });
            probeR.Success.Should().BeTrue(because: $"ffprobe failed: {probeR.Stderr}");

            using var doc = JsonDocument.Parse(probeR.Stdout);
            var root = doc.RootElement;

            // Format duration ≈ sum of kept-segment durations. ExportService
            // tolerates ±200ms internally; we allow 300ms to absorb encoder
            // priming + container rounding without masking real drift.
            var fmtSec = double.Parse(
                root.GetProperty("format").GetProperty("duration").GetString()!,
                CultureInfo.InvariantCulture);
            var actualMs = (long)Math.Round(fmtSec * 1000.0);
            Math.Abs(actualMs - expectedDurMs).Should().BeLessThan(300,
                because: $"output duration {actualMs}ms should be within 300ms of expected {expectedDurMs}ms");

            // Bitrate sanity. libx264 CRF 20 on 1080p broadcast content
            // lands in roughly 4-15 Mbps; the wide band avoids flakes from
            // content-driven bitrate variance while still catching a CRF
            // misconfiguration (CRF 40 ≈ <1 Mbps, CRF 0 ≈ >50 Mbps).
            var bitrate = long.Parse(
                root.GetProperty("format").GetProperty("bit_rate").GetString()!,
                CultureInfo.InvariantCulture);
            bitrate.Should().BeInRange(2_000_000, 25_000_000,
                because: "1080p h264 at CRF 20 should fall in the 2-25 Mbps band");

            // Provenance metadata - comment + creation_time must land in
            // the output's format.tags. comment is asserted exactly because
            // ExportService writes a literal string. creation_time is just
            // checked for presence + parseability (asserting an exact value
            // would race the clock).
            //
            // We use `comment` rather than `encoder` because FFmpeg's MP4
            // muxer always overwrites the `encoder` atom with libavformat's
            // version string regardless of -metadata or FFMETADATA input.
            // See the comment in ExportService.RunExportAsync for the full
            // rationale.
            var formatTags = root.GetProperty("format").GetProperty("tags");
            formatTags.GetProperty("comment").GetString()
                .Should().Be($"Edited by AdTrim {AppVersion.Display}",
                    because: $"ExportService stamps comment=Edited by AdTrim {AppVersion.Display} via -metadata");
            var ctStr = formatTags.GetProperty("creation_time").GetString();
            ctStr.Should().NotBeNullOrWhiteSpace(
                because: "creation_time provenance must reach the output container");
            DateTime.TryParse(
                    ctStr, CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind, out _)
                .Should().BeTrue(
                    because: $"creation_time '{ctStr}' must parse as ISO 8601");

            // Chapters: 3, titled per the kept-segment PartTitles.
            var chapters = root.GetProperty("chapters").EnumerateArray().ToList();
            chapters.Should().HaveCount(3);
            for (int i = 0; i < 3; i++)
            {
                chapters[i].GetProperty("tags").GetProperty("title").GetString()
                    .Should().Be(segments[i].PartTitle);
            }

            // Streams: exactly 1 h264 video at preserved resolution, exactly
            // 1 audio at the source's primary codec, at most 1 data stream
            // (the muxer-added bin_data chapter representation - never the
            // source's bin_data, which was dropped by -map 0:v -map 0:a in
            // the per-segment encoder).
            int videoCount = 0, audioCount = 0, dataCount = 0;
            string? videoCodec = null, audioCodec = null;
            int outWidth = 0, outHeight = 0;
            foreach (var s in root.GetProperty("streams").EnumerateArray())
            {
                var type = s.GetProperty("codec_type").GetString();
                var codec = s.TryGetProperty("codec_name", out var cn) ? cn.GetString() : null;
                switch (type)
                {
                    case "video":
                        videoCount++;
                        videoCodec = codec;
                        outWidth = s.GetProperty("width").GetInt32();
                        outHeight = s.GetProperty("height").GetInt32();
                        break;
                    case "audio":
                        audioCount++;
                        audioCodec = codec;
                        break;
                    case "data":
                        dataCount++;
                        break;
                }
            }
            videoCount.Should().Be(1);
            audioCount.Should().Be(1, because: "primary audio is stream-copied; no extras");
            videoCodec.Should().Be("h264", because: "libx264 strategy must produce h264");
            audioCodec.Should().Be(media.PrimaryAudio.Codec,
                because: "AC3 is stream-copied; codec must match the source's primary");
            outWidth.Should().Be(media.Width, because: "resolution must be preserved");
            outHeight.Should().Be(media.Height);
            dataCount.Should().BeLessThanOrEqualTo(1,
                because: "only the muxer-injected bin_data chapter representation is acceptable; "
                       + "more than one data stream indicates the source's bin_data leaked through");

            // Picture-quality regression net. SSIM the first kept segment of
            // the output against the corresponding source range. Threshold
            // 0.92 absorbs bwdif deinterlace softening + encoder
            // nondeterminism while still catching gross regressions: wrong
            // codec accidentally inserted (SSIM < 0.5), filter chain
            // mangling (< 0.7), CRF misconfigured to a visibly-degraded
            // value (< 0.85), accidental greyscale (< 0.7).
            var ssim = await ComputeSsimAsync(
                runner,
                sourcePath: fixture!,
                srcStartUs: segments[0].StartUs,
                srcDurationUs: segments[0].DurationUs,
                outputPath: outPath,
                outStartUs: 0);
            ssim.Should().BeGreaterThan(0.92,
                because: $"SSIM {ssim:0.0000} below 0.92 indicates a picture-quality regression "
                       + "in the encode path (codec, CRF, filter chain, or pixel format).");

            Sha256(fixture!).Should().Be(hashBefore,
                because: "source must not be modified");
        }
        finally
        {
            try { Directory.Delete(outDir, recursive: true); } catch { /* best effort */ }
        }
    }

    /// <summary>
    /// Smoke test for concat-list path quoting on Windows
    /// paths with spaces and apostrophes. ExportService writes intermediate
    /// paths into concat.txt with forward slashes and escaped single quotes;
    /// the output path goes straight to ffmpeg via ProcessStartInfo's arg
    /// array. This test exercises both: the output path contains a space
    /// AND an apostrophe, and the intermediate dir inherits its parent's
    /// path characteristics.
    ///
    /// One-segment export keeps wall-clock time low (~10s) since the goal
    /// is path-handling, not codec stress.
    /// </summary>
    [SkippableFact]
    public async Task Export_WithSpacesAndApostropheInOutputPath_Succeeds()
    {
        var fixture = FindFixture();
        Skip.If(fixture is null, SkipReason);

        var runner = new FfmpegRunner();
        var probe = new MediaProbeService(runner);
        var encoder = new LibX264EncoderStrategy();
        var export = new ExportService(runner, encoder);

        var media = await probe.ProbeAsync(fixture!);

        // Directory and filename both carry the awkward characters that
        // historically tripped concat-demuxer quoting and shell argument
        // mishandling. The apostrophe in particular is what concat.txt
        // escaping ('\\'') has to get right.
        var outDir = Path.Combine(Path.GetTempPath(), "AdTrim",
            "exp w spaces 'and' quote-" + Guid.NewGuid().ToString("n").Substring(0, 8));
        Directory.CreateDirectory(outDir);
        var outPath = Path.Combine(outDir, "Show Name S01E02 - It's Working.mp4");

        try
        {
            var segments = new[]
            {
                new ExportSegment(0, 0, 5_000_000, "Part 1"),
            };
            var plan = new ExportPlan(
                SourcePath: fixture!,
                OutputPath: outPath,
                SourceDurationUs: media.DurationUs,
                PrimaryAudioStreamIndex: media.PrimaryAudio!.Index,
                KeptSegments: segments,
                FrameRate: media.FrameRate,
                PrimaryAudioCodec: media.PrimaryAudio.Codec);

            await export.RunExportAsync(plan);

            File.Exists(outPath).Should().BeTrue(
                because: "export to a path containing spaces and an apostrophe must succeed");
            new FileInfo(outPath).Length.Should().BeGreaterThan(0);
        }
        finally
        {
            try { Directory.Delete(outDir, recursive: true); } catch { /* best effort */ }
        }
    }

    /// <summary>
    /// Compute SSIM between a source range and an output range using the
    /// ffmpeg ssim lavfi. ssim writes its summary line via av_log at info
    /// level, so we run with -loglevel info and parse stderr for the
    /// "All:N.NNNN" token. Returns the All-channels (Y+U+V combined) SSIM
    /// in [0, 1]. Throws if ffmpeg fails or the summary line is missing.
    /// </summary>
    private static async Task<double> ComputeSsimAsync(
        FfmpegRunner runner,
        string sourcePath, long srcStartUs, long srcDurationUs,
        string outputPath, long outStartUs)
    {
        var srcStartSec = (srcStartUs / 1_000_000.0).ToString("0.000000", CultureInfo.InvariantCulture);
        var outStartSec = (outStartUs / 1_000_000.0).ToString("0.000000", CultureInfo.InvariantCulture);
        var durSec      = (srcDurationUs / 1_000_000.0).ToString("0.000000", CultureInfo.InvariantCulture);

        var args = new[]
        {
            "-hide_banner",
            "-loglevel", "info",
            "-nostats",
            "-ss", outStartSec, "-i", outputPath,
            "-ss", srcStartSec, "-i", sourcePath,
            "-t", durSec,
            "-lavfi", "[0:v][1:v]ssim",
            "-f", "null", "-",
        };
        var r = await runner.RunFfmpegAsync(args);
        if (!r.Success)
            throw new InvalidOperationException(
                $"ffmpeg ssim failed (exit {r.ExitCode}):\n{r.Stderr}");

        var m = Regex.Match(r.Stderr, @"SSIM[^\r\n]*?\bAll:(\d+\.\d+)");
        if (!m.Success)
            throw new InvalidOperationException(
                "SSIM summary line not found in ffmpeg stderr. Output was:\n" + r.Stderr);

        return double.Parse(m.Groups[1].Value, CultureInfo.InvariantCulture);
    }
}
